export const UPAYMENTS_URL =
  "https://upayments-studycase-api.herokuapp.com/api";

export const UPAYMENTS_API_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhYWhpaWwuZGV2QGdtYWlsLmNvbSIsImdpdGh1YiI6Imh0dHBzOi8vZ2l0aHViLmNvbS94c2FhaGlsIiwiaWF0IjoxNjU5ODA4NTI1LCJleHAiOjE2NjAyNDA1MjV9.UU7AznSYcUERD91Zn0k7hxpPQlIw_CH-4W1dyAA42hA";
